version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:2021.04

jobs:
  build_prod:
    executor: my-executor
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install rsync
      - add_ssh_keys:
          fingerprints:
            - SHA256:cYT+MdKiciOdZmO1GtAj42sxDZgb8YLH0UmT+9JMZeU
      - run:
          name: deploy content
          command: |
            rsync app/tempmail/backend -av --delete-after --force -e "ssh -i SHA256:cYT+MdKiciOdZmO1GtAj42sxDZgb8YLH0UmT+9JMZeU -o 'StrictHostKeyChecking no'"  $user@$host:/$dstdir/
      - run:
          name: correct perm
          command: |
            ssh $user@$host -i SHA256:cYT+MdKiciOdZmO1GtAj42sxDZgb8YLH0UmT+9JMZeU  -o 'StrictHostKeyChecking no' chown www-data:www-data -R $dstdir
      - run:
          name: restart service
          command: |
            ssh $user@$host -i SHA256:cYT+MdKiciOdZmO1GtAj42sxDZgb8YLH0UmT+9JMZeU  -o 'StrictHostKeyChecking no' systemctl restart tempmail.service

workflows:
  version: 2.1
  workflow:
    jobs:
      - build_prod:
          filters:
            branches:
              only: main
